FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json* .npmrc* ./
COPY apps/api/package.json ./apps/api/package.json

RUN npm install --workspaces --include-workspace-root=false

COPY apps/api ./apps/api

WORKDIR /app/apps/api

RUN npm run build

EXPOSE 4000

CMD ["node", "dist/index.js"]